# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-03 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TINKOFF', '0004_auto_20180903_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='site_adress',
            field=models.CharField(default='web_site', max_length=30),
        ),
    ]
