# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-16 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TINKOFF', '0005_auto_20180903_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='site_adress',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='phone', max_length=30),
        ),
    ]
