# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-16 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TINKOFF', '0006_auto_20190416_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='eMail', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='\u0424\u0418\u041e', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='power',
            field=models.CharField(default='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='\u0422\u0435\u043b\u0435\u0444\u043e\u043d', max_length=30),
        ),
    ]
